# -*- coding: utf-8 -*-
"""
/***************************************************************************
 shapefile_loader
                                 A QGIS plugin
 loads the Kenyan shapefile
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-01-26
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Group1
        email                : irosetony@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.gui import (QgsLayerTreeMapCanvasBridge, QgsLayerTreeView, QgsMapCanvas, QgsMessageBar)
from qgis.core import (QgsVectorLayer, QgsFeatureRequest)

import locale
import os
import json
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.core import QgsProject
from qgis.utils import iface

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .ShapefileLoader_dialog import shapefile_loaderDialog
import os.path


class shapefile_loader:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'shapefile_loader_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Shapefile_loader')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('shapefile_loader', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/ShapefileLoader/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Shapefile Loader'),
            callback=self.load_file,
            parent=self.iface.mainWindow())

        # will be set False in lao_file()
        self.first_start = True
        
        icon_path = ':/plugins/ShapefileLoader/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'County Identifier'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in identify()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Shapefile Loader'),
                action)
            self.iface.removeToolBarIcon(action)
            self.iface.removePluginVectorMenu(
                self.tr(u'&County Identifier'),
                action)
            self.iface.removeToolBarIcon(action)
    def load_file(self):
        if self.first_start == True:
            self.first_start = False
    
        """Method that opens the browse window to select file"""
        #Open the file browser window
        filename1 = QFileDialog.getOpenFileName( filter="*.shp")
        #Get the first value of the turple and convert to string
        getpath = "{}".format(filename1[0])
        #Load map 
        vlayer = iface.addVectorLayer(getpath, "Shapefile", "ogr")

             
    def run(self):
        """Run method that identifies counties and display"""

       # Create the dialog with elements (after translation) and keep reference
        if self.first_start == True:
            self.first_start = False
            self.dlg = shapefile_loaderDialog()
        self.dlg.label.setText("")
        layer = iface.activeLayer()
        name1 =""
        #cc1 = []
        #for i in range(0, 47):
        feat = layer.getFeature(19)
        name1 = feat['NAME_1']
            #cc1 = feat['CC_1']
        #mbsa_id = 1
        #mbsa_ind = cc1.index[mbsa_id]
        #mbsa_name = name1[]
            
        message = "YOU ARE FROM {} COUNTY.".format(name1)
        self.dlg.label.setText(message)
                
        

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed

        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
